name: Run Pre-Commit Hooks

on:
  push:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          
      - name : Desploy Terraform
        run: |
         terraform init
         terraform validate
         terraform plan
