name: Run Pre-Commit Hooks

on:
  push:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.5

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.44.1

    - name: Run TFLint.
      run: | 
        tflint --init
        tflint
    
    - name: Test with Checkov
      continue-on-error: true
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        framework: terraform
